export enum MstTheme {
  mc_header_height = "64px",
  mc_sidebar_width = "138px",
  mc_primary_color = "#1ea7c9",
  mc_grey_color = "#216783",
  mc_dark_color = "#010327",
  mc_label_color = "#fff8f0",
  mc_title_color = "#fff8f0",
  mc_title_bg_color = "#2d849e",
  mc_text_color = "#fafafa",
  mc_numbers_color = "#68e9de",
  mc_black_bg_color = "#1a1a1a",
  mc_green_color = "#59db4d",
  mc_danger_color = "#ec6f6f",
  mc_warning_color = "#f09f26",
  mc_active_color = "#41f8e6",
}
