module.exports = {
  "disabled-bg": "#B7B7B7",
  "primary-color": "#4ebd22",
  "disabled-color": "#AFAFAF",
  "label-color": "rgba(255, 255, 255, 0.7)",
  "layout-header-background": "#184223",
  "layout-body-background": "#0a3010",
  "layout-header-padding": "0",
  "layout-header-height": "68px",
  "modal-header-bg": "#505788",
  "modal-body-padding": "16px",
  "btn-ghost-color": "#0091FF",
  "btn-ghost-border": "#0091FF",
  "modal-heading-color": "rgba(255, 255, 255, 0.7)",
  "font-family": "\"PingFangSC-Medium\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", \"Helvetica Neue\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
};
